version: 0.2
env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "http://portfolio-dev-build.s3-website-eu-west-1.amazonaws.com"
        BUILD_FOLDER: "dev-build"
        BUILD_ENV: "dev"
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp ${BUILD_FOLDER} s3://${S3_BUCKET} --recursive --acl public-read --cache-control "max-age=${CACHE_CONTROL}"
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
